# Generated by Django 4.2.3 on 2023-08-01 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scraping", "0002_remove_news_created_at_remove_news_published_and_more"),
    ]

    operations = [
        migrations.DeleteModel(name="News",),
    ]
