# Generated by Django 4.1.6 on 2023-08-11 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("URLsub", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="urlsub", name="tags",),
        migrations.AddField(
            model_name="urlsub",
            name="tags",
            field=models.CharField(blank=True, default="", max_length=200, null=True),
        ),
    ]
