# Generated by Django 4.2.5 on 2023-12-27 05:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("StripePayment", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="product_files/"),
        ),
        migrations.AddField(
            model_name="product",
            name="url",
            field=models.URLField(default="default_value_here"),
        ),
    ]
