# Generated by Django 4.2.5 on 2024-02-22 16:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("StripePayment", "0002_alter_subscription_completed_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="subscription_plan_id",
            field=models.CharField(max_length=100),
        ),
    ]
