# Generated by Django 4.2.5 on 2023-12-28 21:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("StripePayment", "0003_alter_product_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="url",
        ),
    ]
