# Generated by Django 4.2.5 on 2023-12-28 22:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("StripePayment", "0004_remove_product_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="file",
        ),
    ]
