# Generated by Django 4.2.5 on 2023-12-30 02:52

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("StripePayment", "0005_remove_product_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="price",
            name="price",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=10
            ),
        ),
    ]
