# Generated by Django 4.2.5 on 2024-01-03 18:58

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("StripePayment", "0006_alter_price_price"),
    ]

    operations = [
        migrations.CreateModel(
            name="Donation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "donation_type",
                    models.CharField(
                        choices=[
                            ("one-off", "One-off"),
                            ("monthly", "Monthly Subscription"),
                        ],
                        max_length=10,
                    ),
                ),
            ],
        ),
    ]
