# Generated by Django 4.2.5 on 2024-01-23 18:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("StripePayment", "0007_donation"),
    ]

    operations = [
        migrations.AddField(
            model_name="donation",
            name="stripe_checkout_session_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="donation",
            name="subscription_plan_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="donation",
            name="subscription_start_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
