# Generated by Django 4.2.5 on 2024-01-25 00:08

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("StripePayment", "0008_donation_stripe_checkout_session_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="donation",
            name="donation_type",
        ),
        migrations.RemoveField(
            model_name="donation",
            name="subscription_plan_id",
        ),
        migrations.RemoveField(
            model_name="donation",
            name="subscription_start_date",
        ),
        migrations.AddField(
            model_name="donation",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                ("subscription_plan_id", models.CharField(max_length=100)),
                ("stripe_checkout_session_id", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
