# Generated by Django 4.2.5 on 2024-01-25 00:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("StripePayment", "0009_remove_donation_donation_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="subscription",
            name="stripe_subscription_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
