# Generated by Django 4.2.5 on 2024-01-28 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("StripePayment", "0011_donation_checkout_status_donation_completed_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="StripePayment.product",
            ),
        ),
    ]
