#blog/production_settings.py
"""
PRODUCTION ENVIRONMENT SETTINGS
These are the settings for the production environment
Django settings for blog project.

Generated by 'django-admin startproject' using Django 4.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path
import os
import sys # new
from elasticsearch_dsl import connections
from decouple import config



import dj_database_url


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent



# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
#BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY')

#SECRET_KEY = "django-insecure-n1(8673js4qwf9ud3%7em!s(=)jr%^%d0^t^uxu)p+vj^(-kdb" #This is the default key

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG=False
#DEBUG = config('DEBUG', default=False, cast=bool)
print(DEBUG)
print("made it here")

ALLOWED_HOSTS = [ 'jidder.onrender.com']

RENDER_EXTERNAL_HOSTNAME = os.environ.get('RENDER_EXTERNAL_HOSTNAME')
if RENDER_EXTERNAL_HOSTNAME:
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)

print("RENDER_EXTERNAL_HOSTNAME:", RENDER_EXTERNAL_HOSTNAME)

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    'django_elasticsearch_dsl',
    'taggit',
    'apps.users',
    'apps.core',
   # 'scraping',
    'apps.Search',
    'apps.ContactUs',
    'apps.URLsub',
    'widget_tweaks',
    'timezone_field',



]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    'whitenoise.middleware.WhiteNoiseMiddleware',
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    

]

ROOT_URLCONF = "blog.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / 'templates'],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "blog.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': os.environ.get('DB_NAME'),
        'USER': os.environ.get('DB_USER'),
        'PASSWORD': os.environ.get('DB_PASSWORD'),
        'HOST': os.environ.get('DB_HOST'),
        'PORT': os.environ.get('DB_PORT'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",},
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True



# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

AUTH_USER_MODEL = 'users.User'

MEDIA_ROOT = BASE_DIR / 'media'
MEDIA_URL = '/media/'

EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

LOGIN_URL = "/users/login"

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/



#STATICFILES_DIRS = (BASE_DIR / 'static',)
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

# This setting tells Django at which URL static files are going to be served to the user.
# Here, they well be accessible at your-domain.onrender.com/static/...
STATIC_URL = '/static/'
# Following settings only make sense on production and may break development environments.
    # in your application directory on Render.
#STATIC_ROOT = os.path.join(BASE_DIR, 'assets')
    # Turn on WhiteNoise storage backend that takes care of compressing static files
    # and creating unique names for each version so they can safely be cached forever.
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
    os.path.join(BASE_DIR, "static/css/"),
    os.path.join(BASE_DIR, "static/img/"),
    os.path.join(BASE_DIR, "static/js/"),
   
]

STATICFILES_STORAGE = 'whitenoise.storage.CompressedStaticFilesStorage'



STATIC_ROOT = os.path.join(BASE_DIR, 'static_collected')

# Enable WhiteNoise compression for CSS and JS (optional, but recommended for production)
WHITE_NOISE_USE_FINDERS = True

# Compress files served via WhiteNoise (optional, but recommended)
WHITE_NOISE_USE_GZIP = True

# Debugging static file settings
print(f"STATIC_URL: {STATIC_URL}")
print(f"STATIC_ROOT: {STATIC_ROOT}")
print(f"STATICFILES_DIRS: {STATICFILES_DIRS}")
print(f"STATICFILES_STORAGE: {STATICFILES_STORAGE}")
print(f"WHITE_NOISE_USE_FINDERS: {WHITE_NOISE_USE_FINDERS}")
print(f"WHITE_NOISE_USE_GZIP: {WHITE_NOISE_USE_GZIP}")


# save Celery task results in Django's database
CELERY_RESULT_BACKEND = "django-db"

# This configures Redis as the datastore between Django + Celery
#CELERY_BROKER_URL = Config('CELERY_BROKER_REDIS_URL', default='redis://localhost:6379')
# if you out to use os.environ the config is:
# CELERY_BROKER_URL = os.environ.get('CELERY_BROKER_REDIS_URL', 'redis://localhost:6379')


# this allows you to schedule items in the Django admin.
CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers.DatabaseScheduler'

EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'


sys.path.append(os.path.join(BASE_DIR, 'apps')) # at the bottom of the file


ELASTICSEARCH_DSL={
     'default': {
        'hosts': 'jidder-elasticsearch:9200',
    },
}

# Debugging Elasticsearch configuration
print(f"ELASTICSEARCH_DSL: {ELASTICSEARCH_DSL}")



# Define an Elasticsearch connection
#connections.create_connection(
 #   hosts=['srv-ckeah4mnpffc73ad5o0g-5fddc575c7-qpc8c:9200'],  # Replace with your Elasticsearch server's URL and port
  #  timeout=20,
   # verify_certs=False, 
#)

print("Using production settings")