# Generated by Django 4.2.3 on 2023-08-01 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scraping", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="news", name="created_at",),
        migrations.RemoveField(model_name="news", name="published",),
        migrations.RemoveField(model_name="news", name="updated_at",),
    ]
