# Generated by Django 4.2.3 on 2023-08-01 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("scraping", "0003_delete_news"),
    ]

    operations = [
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("link", models.CharField(default="", max_length=2083, unique=True)),
                (
                    "source",
                    models.CharField(blank=True, default="", max_length=30, null=True),
                ),
            ],
        ),
    ]
