# Generated by Django 4.2.5 on 2023-12-11 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("URLsub", "0013_urlsub_slug"),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="urlsub",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="related_posts",
                to="URLsub.urlsub",
            ),
        ),
    ]
