# Generated by Django 4.2.5 on 2023-09-27 03:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_userpostinteraction"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserPostInteraction",
        ),
    ]
