# Generated by Django 4.2.3 on 2023-08-01 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_news"),
    ]

    operations = [
        migrations.DeleteModel(name="News",),
    ]
