# Generated by Django 4.1.6 on 2023-08-08 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_contact"),
    ]

    operations = [
        migrations.DeleteModel(name="Contact",),
    ]
