# Generated by Django 4.1.6 on 2023-08-26 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_delete_contact"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlogFullRecommend",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(db_index=True, max_length=200)),
                ("url", models.URLField(db_index=True)),
                ("author", models.CharField(blank=True, db_index=True, max_length=200)),
                ("content", models.TextField(blank=True, max_length=500)),
                ("image", models.ImageField(blank=True, null=True, upload_to="")),
                ("created_on", models.DateTimeField(blank=True)),
                ("tags", models.ManyToManyField(blank=True, to="core.tag")),
            ],
            options={"ordering": ["-created_on"],},
        ),
    ]
