# Generated by Django 4.1.6 on 2023-08-28 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_rename_author_post_username"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blogfullrecommend", options={"ordering": ["-last_updated"]},
        ),
        migrations.RenameField(
            model_name="blogfullrecommend",
            old_name="created_on",
            new_name="last_updated",
        ),
    ]
