# Generated by Django 4.1.6 on 2023-09-14 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_alter_blogfullrecommend_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment", old_name="username", new_name="author",
        ),
        migrations.RenameField(
            model_name="post", old_name="username", new_name="author",
        ),
    ]
