# Generated by Django 4.1.6 on 2023-09-18 18:54

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ("taggit", "0005_auto_20220424_2025"),
        ("core", "0011_rename_username_comment_author_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="tag", name="name",),
        migrations.AddField(
            model_name="tag",
            name="tags",
            field=taggit.managers.TaggableManager(
                help_text="A comma-separated list of tags.",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
    ]
