# Generated by Django 4.1.6 on 2023-09-12 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_options_alter_user_managers_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="avatar",
            field=models.ImageField(blank=True, null=True, upload_to="avatars/"),
        ),
        migrations.AddField(
            model_name="profile",
            name="interests",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="profile",
            name="personal_description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="profile", name="about_me", field=models.TextField(blank=True),
        ),
    ]
