# Generated by Django 4.1.6 on 2023-09-13 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_profile_avatar_profile_interests_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="profile", name="personal_description",),
    ]
