# Generated by Django 4.1.6 on 2023-09-14 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_remove_profile_personal_description"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile", old_name="image", new_name="banner",
        ),
    ]
