# Generated by Django 4.1.6 on 2023-09-14 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_rename_image_profile_banner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="banner",
            field=models.ImageField(blank=True, null=True, upload_to="banners/"),
        ),
    ]
