# Generated by Django 4.1.6 on 2023-09-14 20:21

from django.db import migrations
import timezone_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_profile_timezone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="timezone",
            field=timezone_field.fields.TimeZoneField(default="UTC"),
        ),
    ]
