# Generated by Django 4.1.6 on 2023-09-20 18:46

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ("taggit", "0005_auto_20220424_2025"),
        ("URLsub", "0002_remove_urlsub_tags_urlsub_tags"),
    ]

    operations = [
        migrations.RemoveField(model_name="urlsub", name="url",),
        migrations.AddField(
            model_name="urlsub",
            name="url",
            field=taggit.managers.TaggableManager(
                help_text="A comma-separated list of tags.",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
    ]
