# Generated by Django 4.1.6 on 2023-09-20 19:00

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ("taggit", "0005_auto_20220424_2025"),
        ("URLsub", "0003_remove_urlsub_url_urlsub_url"),
    ]

    operations = [
        migrations.RemoveField(model_name="urlsub", name="tags",),
        migrations.RemoveField(model_name="urlsub", name="url",),
        migrations.AddField(
            model_name="urlsub",
            name="tags",
            field=taggit.managers.TaggableManager(
                help_text="A comma-separated list of tags.",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
        migrations.AddField(
            model_name="urlsub",
            name="url",
            field=models.CharField(blank=True, default="", max_length=200, null=True),
        ),
    ]
