# Generated by Django 4.2.5 on 2023-10-31 02:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("URLsub", "0004_remove_urlsub_tags_remove_urlsub_url_urlsub_tags_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="urlsub",
            options={"verbose_name_plural": "URL Submissions"},
        ),
    ]
