# Generated by Django 4.2.5 on 2023-11-02 17:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("URLsub", "0005_alter_urlsub_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="urlsub",
            options={},
        ),
        migrations.RenameField(
            model_name="urlsub",
            old_name="username",
            new_name="user",
        ),
        migrations.AddField(
            model_name="urlsub",
            name="recommendations_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="urlsub",
            name="url",
            field=models.TextField(default="", unique=True),
        ),
    ]
