# Generated by Django 4.2.5 on 2023-11-03 16:18

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):
    dependencies = [
        ("taggit", "0005_auto_20220424_2025"),
        ("URLsub", "0007_alter_urlsub_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="urlsub",
            name="tags",
            field=taggit.managers.TaggableManager(
                help_text="A comma-separated list of tags.",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
        migrations.AlterField(
            model_name="urlsub",
            name="url",
            field=models.URLField(),
        ),
        migrations.AlterUniqueTogether(
            name="urlsub",
            unique_together={("url", "description")},
        ),
    ]
