# Generated by Django 4.2.5 on 2023-11-27 17:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("URLsub", "0011_urlsub_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="urlsub",
            name="title",
            field=models.TextField(),
        ),
    ]
