# Generated by Django 4.2.5 on 2024-03-12 04:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("URLsub", "0014_tag_description"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="description",
            options={"ordering": ["-urlsub__timestamp"]},
        ),
    ]
