# Generated by Django 4.2.5 on 2024-03-12 04:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("URLsub", "0015_alter_description_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="description",
            options={"ordering": ["-timestamp"]},
        ),
        migrations.AddField(
            model_name="description",
            name="timestamp",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
