# Generated by Django 4.2.5 on 2024-03-21 00:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("URLsub", "0016_alter_description_options_description_timestamp"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="description",
            unique_together=set(),
        ),
    ]
